sonar.projectKey=three-tier-project
sonar.projectName=Three-Tier-Project
sonar.sourceEncoding=UTF-8

sonar.sources=backend/src/main/java,frontend,terraform
sonar.tests=backend/src/test/java
sonar.java.binaries=backend/target/classes
sonar.java.libraries=backend/target/backend-app-1.0.jar
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml

sonar.exclusions=**/target/**,**/.git/**,**/.mvn/**,**/.terraform/**
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
