sonar.projectName=Three-Tier-Project

sonar.sources=backend/src/main/java,frontend
sonar.tests=backend/src/test/java

sonar.java.binaries=backend/target/classes
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml

sonar.exclusions=**/target/**,**/.git/**,**/.mvn/**
sonar.sourceEncoding=UTF-8

sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
